EMR/Controllers/LoginController.cs
using EMR.DAL2.EF;
using EMR.DAL2.Identity;
using EMR.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EMR.Controllers
{
    public class LoginController : BaseController
    {
        // GET: Login
        public ActionResult Index()
        {
            AppUser usr_new = new AppUser() { Name = "Admin", UserName = "Adm", Role_Id = "1" };
            UserManager.Create(usr_new, "111111");
            AppUser usr_new2 = new AppUser() { Name = "Doc", UserName = "Doc", Role_Id = "2" };
            UserManager.Create(usr_new2, "111111");
            return View();
        }

        public ActionResult SignIn()
        {
            

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SignIn(LoginViewModel login, String ReturnUrl)
        {
            AppUser usr = UserManager.Find(login.UserName, login.Password);
            if (usr == null || login.UserName == null || login.Password == null)
            {
                ModelState.AddModelError("Error", "Логин или пароль неправильные");
                return View();
            }
            ClaimsIdentity ident = await UserManager.CreateIdentityAsync(usr, DefaultAuthenticationTypes.ApplicationCookie);
            AuthManager.SignOut();
            AuthManager.SignIn(new AuthenticationProperties
            {
                IsPersistent = false
            }, ident);

            if (Url.IsLocalUrl(ReturnUrl))
            {
                return Redirect(ReturnUrl);
            }

            return RedirectToAction("Index", "Main");
        }

        public ActionResult SignOut()
        {
            AuthManager.SignOut();
            return RedirectToAction("SignIn");
        }

        //private AppRole GetCurrentRole()
        //{
        //    AppUser user = new AppUser();
        //    user = UserManager.FindById(User.Identity.GetUserId());
        //    if (user == null)
        //    {
        //        user = new AppUser() { Id = "0" };
        //        //user.Role = new EMRContext().AppRoles.Find("8");
        //        user.Role = new AppRole();
        //    }
        //    return user.Role;
        //}

        //private EMRContext UserContext
        //{
        //    get
        //    {
        //        return HttpContext.GetOwinContext().GetUserManager<EMRContext>();
        //    }
        //}
        //private IAuthenticationManager AuthManager
        //{
        //    get
        //    {
        //        return HttpContext.GetOwinContext().Authentication;
        //    }
        //}
        //private AppUserManager UserManager
        //{
        //    get
        //    {
        //        return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
        //    }
        //}

    }
}

EMR/Controllers/MainController.cs
using EMR.DAL2.EF;
using EMR.DAL2.Identity;
using EMR.DAL2.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EMR.Controllers
{
    [Authorize]
    public class MainController : BaseController, IController
    {
        private IUnitOfWork db;
        public MainController(IUnitOfWork unitOfWork)
        {
            db = unitOfWork;
        }       
        
        // GET: Main
        public ActionResult Index()
        {
            AppUser usr = GetCurrentUser();
            ViewBag.User = usr;
            return View();
        }

        public ActionResult Visitors()
        {
            AppUser usr = GetCurrentUser();
            ViewBag.User = usr;


            return View();
        }
    }
}

EMR/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMR.DAL2.EF;
using EMR.DAL2.Identity;
using EMR.DAL2.Interfaces;
using Microsoft.AspNet.Identity;
using EMR.Models;

namespace EMR.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {

        private IUnitOfWork uow;
        private Lazy<EMRContext> db = new Lazy<EMRContext>();
        public UsersController(IUnitOfWork unitOfWork)
        {
            uow = unitOfWork;
        }

        // GET: Users
        public ActionResult Index()
        {
            ViewBag.User = GetCurrentUser();
            return View();
        }

        [HttpPost]
        public ActionResult UserList(String filter)
        {
            IEnumerable<AppUser> users = UserManager.Users.Where(u => u.Name.Contains(filter) || u.UserName.Contains(filter)).OrderBy(u => u.Role_Id).OrderBy(u => u.Name).ToList();
            return View(users);
        }

        public ActionResult Create()
        {
            ViewBag.Roles = db.Value.AppRoles.ToList().Select(d => new SelectListItem() { Value = d.Id.ToString(), Text = d.Name }).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(UserViewModel user)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Roles = db.Value.AppRoles.ToList().Select(d => new SelectListItem() { Value = d.Id.ToString(), Text = d.Name }).ToList();
                return View(user);
            }

            AppUser usr_new = new AppUser() { Name = user.Name, UserName = user.UserName, Role_Id = user.Role_Id };
            UserManager.Create(usr_new, user.Password);
            return Json(1);
        }

        public ActionResult Edit(String Id)
        {
            AppUser usr = UserManager.Users.FirstOrDefault(u => u.Id == Id);
            UserEditModel view = new UserEditModel() { UserId = usr.Id, Name = usr.Name, UserName = usr.UserName, Role_Id = usr.Role_Id };
            ViewBag.Roles = db.Value.AppRoles.ToList().Select(d => new SelectListItem() { Value = d.Id.ToString(), Text = d.Name }).ToList();
            return View(view);
        }

        [HttpPost]
        public ActionResult Edit(UserEditModel user)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Roles = db.Value.AppRoles.ToList().Select(d => new SelectListItem() { Value = d.Id.ToString(), Text = d.Name }).ToList();
                return View(user);
            }

            AppUser usr_new = UserManager.Users.FirstOrDefault(u => u.Id == user.UserId);
            usr_new.Name = user.Name;
            usr_new.UserName = user.UserName;
            usr_new.Role_Id = user.Role_Id;
            UserManager.Update(usr_new);
            return Json(1);
        }


        public ActionResult Delete(String Id)
        {
            if (UserManager.Delete(UserManager.Users.FirstOrDefault(u => u.Id == Id)).Succeeded)
            {
                return Json(1, JsonRequestBehavior.AllowGet);
            }
            else return Json(0, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ResetPwd(String Id)
        {
            UserManager.RemovePassword(Id);
            UserManager.AddPassword(Id, "111111");
            return Json(1, JsonRequestBehavior.AllowGet);
        }
    }
}

EMR/Views/Shared/_Header.cshtml
@model EMR.DAL2.Identity.AppUser

<header class="topnavbar-wrapper">
    <!-- START Top Navbar-->
    <nav class="navbar topnavbar" role="navigation">
        <!-- START navbar header-->
        <div class="navbar-header">
            <a class="navbar-brand" href="#/">
                <div class="brand-logo">
                    <img class="img-fluid" src="~/Content/img/logo.svg" alt="App Logo" style="max-height: 35px">
                </div>
                <div class="brand-logo-collapsed">
                    <img class="img-fluid" src="~/Content/img/logo-single.png" alt="App Logo">
                </div>
            </a>
        </div>
        <!-- END navbar header-->
        <!-- START Left navbar-->
        <ul class="navbar-nav mr-auto flex-row">
            <li class="nav-item">
                <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed">
                    <em class="fa fa-navicon"></em>
                </a>
                <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true">
                    <em class="fa fa-navicon"></em>
                </a>
            </li>
            <!-- START User avatar toggle-->
            <li class="nav-item d-none d-md-block">
                <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                <a class="nav-link" id="user-block-toggle" href="#user-block" data-toggle="collapse">
                    <em class="icon-user"></em>
                </a>
            </li>
            <!-- END User avatar toggle-->
            <!-- START lock screen-->
            <li class="nav-item d-none d-md-block">
                <a class="nav-link" href="@Url.Action("SignOut", "Login")" title="Выход">
                    <em class="icon-logout"></em>
                </a>
            </li>
            <!-- END lock screen-->
        </ul>
        <!-- END Left navbar-->
        <!-- START Right Navbar-->
        <ul class="navbar-nav flex-row">
            <!-- Search icon-->
            <li class="nav-item">
                <a class="nav-link" href="#" data-search-open="">
                    <em class="icon-magnifier"></em>
                </a>
            </li>
            <!-- Fullscreen (only desktops)-->
            <li class="nav-item d-none d-md-block">
                <a class="nav-link" href="#" data-toggle-fullscreen="">
                    <em class="fa fa-expand"></em>
                </a>
            </li>
            <!-- START Alert menu-->
            <li class="nav-item dropdown dropdown-list">
                <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" data-toggle="dropdown">
                    <em class="icon-bell"></em>
                    <span class="badge badge-danger">11</span>
                </a>
                <!-- START Dropdown menu-->
                <div class="dropdown-menu dropdown-menu-right animated flipInX">
                    <div class="dropdown-item">
                        <!-- START list group-->
                        <div class="list-group">
                            <!-- list item-->
                            <div class="list-group-item list-group-item-action">
                                <div class="media">
                                    <div class="align-self-start mr-2">
                                        <em class="fa fa-twitter fa-2x text-info"></em>
                                    </div>
                                    <div class="media-body">
                                        <p class="m-0">New followers</p>
                                        <p class="m-0 text-muted text-sm">1 new follower</p>
                                    </div>
                                </div>
                            </div>
                            <!-- list item-->
                            <div class="list-group-item list-group-item-action">
                                <div class="media">
                                    <div class="align-self-start mr-2">
                                        <em class="fa fa-envelope fa-2x text-warning"></em>
                                    </div>
                                    <div class="media-body">
                                        <p class="m-0">New e-mails</p>
                                        <p class="m-0 text-muted text-sm">You have 10 new emails</p>
                                    </div>
                                </div>
                            </div>
                            <!-- list item-->
                            <div class="list-group-item list-group-item-action">
                                <div class="media">
                                    <div class="align-self-start mr-2">
                                        <em class="fa fa-tasks fa-2x text-success"></em>
                                    </div>
                                    <div class="media-body">
                                        <p class="m-0">Pending Tasks</p>
                                        <p class="m-0 text-muted text-sm">11 pending task</p>
                                    </div>
                                </div>
                            </div>
                            <!-- last list item-->
                            <div class="list-group-item list-group-item-action">
                                <span class="d-flex align-items-center">
                                    <span class="text-sm">More notifications</span>
                                    <span class="badge badge-danger ml-auto">14</span>
                                </span>
                            </div>
                        </div>
                        <!-- END list group-->
                    </div>
                </div>
                <!-- END Dropdown menu-->
            </li>
            <!-- END Alert menu-->
            <!-- START Offsidebar button-->
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
                    <em class="icon-notebook"></em>
                </a>
            </li>
            <!-- END Offsidebar menu-->
        </ul>
        <!-- END Right Navbar-->
        <!-- START Search form-->
        <form class="navbar-form" role="search" action="http://themicon.co/theme/angle/v3.8.7/html5jquery-bs4/app/search.html">
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Введите текст и нажмите ВВОД ...">
                <div class="fa fa-times navbar-form-close" data-search-dismiss=""></div>
            </div>
            <button class="d-none" type="submit">Ввод</button>
        </form>
        <!-- END Search form-->
    </nav>
    <!-- END Top Navbar-->
</header>
<!-- sidebar-->

EMR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>@ViewBag.Title - ЭАК</title>
    @Styles.Render("~/Content/css")

</head>
<body class="-text">
    <div class="wrapper">
        @RenderBody()       
    </div>

    @Scripts.Render("~/bundles/js")
</body>
</html>

EMR/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>@ViewBag.Title - ЭАК</title>
    <link rel="shortcut icon" type="image/png" href="~/Content/img/favicon.ico" />
    @Styles.Render("~/Content/css")
    <!-- =============== BOOTSTRAP STYLES ===============-->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css" id="bscss">
    <!-- =============== APP STYLES ===============-->
    <link rel="stylesheet" href="~/Content/css//app.css" id="maincss">
</head>
<body>
    <div class="wrapper">
        @{Html.RenderPartial("_Header", (EMR.DAL2.Identity.AppUser)ViewBag.User);}
        @{Html.RenderPartial("_Menu", (EMR.DAL2.Identity.AppUser)ViewBag.User);}
        @{Html.RenderPartial("_OffSideBar");}

        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jsMain")
    <footer class="footer-container">
        <span>&copy; 2018 - ЭАК</span>
    </footer>

    <div id="overlay" style="display:none; z-index:999;">       
        <div id="loading-img" class="card-body whirl traditional">

        </div>
    </div>   

</body>
</html>

EMR/Views/Shared/_Menu.cshtml
@model EMR.DAL2.Identity.AppUser


<aside class="aside-container">
    <!-- START Sidebar (left)-->
    <div class="aside-inner">
        <nav class="sidebar" data-sidebar-anyclick-close="">
            <!-- START sidebar nav-->
            <ul class="sidebar-nav">
                <!-- START user info-->
                <li class="has-user-block">
                    <div class="collapse" id="user-block">
                        <div class="item user-block">
                            <!-- User picture-->
                            <div class="user-block-picture">
                                <div class="user-block-status">
                                    <img class="img-thumbnail rounded-circle" src="~/Content/img/user/02.jpg" alt="Avatar" width="60" height="60">
                                    <div class="circle bg-success circle-lg"></div>
                                </div>
                            </div>
                            <!-- Name and Job-->
                            <div class="user-block-info">
                                <span class="user-block-name">Привет, @Model.UserName</span>
                                <span class="user-block-role">@Model.Role.Name</span>
                            </div>
                        </div>
                    </div>
                </li>
                <!-- END user info-->
                <!-- Iterates over all sidebar items-->
                <li class="nav-heading">
                     <span data-localize="sidebar.heading.HEADER">Меню</span>
                </li>
                <li class=" ">
                    <a href="@Url.Action("Index", "Main")" title="Главная">
                        <em class="icon-control-start"></em>
                        <span data-localize="sidebar.nav.WIDGETS">Главная</span>
                    </a>
                </li>
                <li class=" ">
                    <a href="@Url.Action("Visitors", "Main")" data-ajax="true" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#mainContent"  title="Приемы">
                        <div class="float-right badge badge-success">3</div>
                        <em class="icon-user-follow"></em>
                        <span data-localize="sidebar.nav.WIDGETS">Приемы</span>
                    </a>
                </li>
                <!--Admin area menu-->
                <li class="nav-heading ">
                    <span data-localize="sidebar.heading.COMPONENTS">Администрирование</span>
                </li>
                <li class=" ">
                    <a href="@Url.Action("Index", "Users")" title="Widgets">                        
                        <em class="icon-user"></em>
                        <span data-localize="sidebar.nav.WIDGETS">Пользователи ЭАК</span> 
                    </a>
                </li>
                <li class=" ">
                    <a href="widgets.html" title="Widgets">                       
                        <em class="icon-settings"></em>
                        <span data-localize="sidebar.nav.WIDGETS">Параметры</span>
                    </a>
                </li>
                         
                
            </ul>
            <!-- END sidebar nav-->
        </nav>
    </div>
    <!-- END Sidebar (left)-->
</aside>

EMR/Views/Shared/_OffSideBar.cshtml
<aside class="offsidebar d-none">
    <!-- START Off Sidebar (right)-->
    <nav>
        <div role="tabpanel">
            <!-- Nav tabs-->
            <ul class="nav nav-tabs nav-justified" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" href="#app-settings" aria-controls="app-settings" role="tab" data-toggle="tab">
                        <em class="icon-equalizer fa-lg"></em>
                    </a>
                </li>
            </ul>
            <!-- Tab panes-->
            <div class="tab-content">
                <div class="tab-pane fade active show" id="app-settings" role="tabpanel">
                    <h3 class="text-center text-thin mt-4">Settings</h3>
                    <div class="p-2">
                        <h4 class="text-muted text-thin">Themes</h4>
                        <div class="row row-flush mb-2">
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-a.css">
                                        <input type="radio" name="setting-theme" checked="checked">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-info"></span>
                                            <span class="color bg-info-light"></span>
                                        </span>
                                        <span class="color bg-white"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-b.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-green"></span>
                                            <span class="color bg-green-light"></span>
                                        </span>
                                        <span class="color bg-white"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-c.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-purple"></span>
                                            <span class="color bg-purple-light"></span>
                                        </span>
                                        <span class="color bg-white"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-d.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-danger"></span>
                                            <span class="color bg-danger-light"></span>
                                        </span>
                                        <span class="color bg-white"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row row-flush mb-2">
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-e.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-info-dark"></span>
                                            <span class="color bg-info"></span>
                                        </span>
                                        <span class="color bg-gray-dark"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-f.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-green-dark"></span>
                                            <span class="color bg-green"></span>
                                        </span>
                                        <span class="color bg-gray-dark"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-g.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-purple-dark"></span>
                                            <span class="color bg-purple"></span>
                                        </span>
                                        <span class="color bg-gray-dark"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="col mb-2">
                                <div class="setting-color">
                                    <label data-load-css="../Content/css/theme-h.css">
                                        <input type="radio" name="setting-theme">
                                        <span class="icon-check"></span>
                                        <span class="split">
                                            <span class="color bg-danger-dark"></span>
                                            <span class="color bg-danger"></span>
                                        </span>
                                        <span class="color bg-gray-dark"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="p-2">
                        <h4 class="text-muted text-thin">Layout</h4>
                        <div class="clearfix">
                            <p class="float-left">Fixed</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-fixed" type="checkbox" data-toggle-state="layout-fixed">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="float-left">Boxed</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-boxed" type="checkbox" data-toggle-state="layout-boxed">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="float-left">RTL</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-rtl" type="checkbox">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="p-2">
                        <h4 class="text-muted text-thin">Aside</h4>
                        <div class="clearfix">
                            <p class="float-left">Collapsed</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-collapsed" type="checkbox" data-toggle-state="aside-collapsed">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="float-left">Collapsed Text</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-collapsed-text" type="checkbox" data-toggle-state="aside-collapsed-text">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="float-left">Float</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-float" type="checkbox" data-toggle-state="aside-float">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="float-left">Hover</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-hover" type="checkbox" data-toggle-state="aside-hover">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                        <div class="clearfix">
                            <p class="float-left">Show Scrollbar</p>
                            <div class="float-right">
                                <label class="switch">
                                    <input id="chk-hover" type="checkbox" data-toggle-state="show-scrollbar" data-target=".sidebar">
                                    <span></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- END Off Sidebar (right)-->
</aside>